DEF NUM_PLAYER_NAMES EQU 3

IF DEF(_JAPAN)
	DEF PLAYERNAME1 EQUS "イエロー"
	DEF PLAYERNAME2 EQUS "サトシ"
	DEF PLAYERNAME3 EQUS "ジャック"
	DEF RIVALNAME1 EQUS "ブルー"
	DEF RIVALNAME2 EQUS "シゲル"
	DEF RIVALNAME3 EQUS "ジョン"
ELIF DEF(_FRENCH)
	DEF PLAYERNAME1 EQUS "YELLOW"
	DEF PLAYERNAME2 EQUS "SACHA"
	DEF PLAYERNAME3 EQUS "PAUL"
	DEF RIVALNAME1 EQUS "BLUE"
	DEF RIVALNAME2 EQUS "REGIS"
	DEF RIVALNAME3 EQUS "JEAN"
ELIF DEF(_GERMAN)
	DEF PLAYERNAME1 EQUS "GELB"
	DEF PLAYERNAME2 EQUS "ASH"
	DEF PLAYERNAME3 EQUS "JACK"
	DEF RIVALNAME1 EQUS "BLAU"
	DEF RIVALNAME2 EQUS "GARY"
	DEF RIVALNAME3 EQUS "JOHN"
ELIF DEF(_ITALIAN)
	DEF PLAYERNAME1 EQUS "GIALLO"
	DEF PLAYERNAME2 EQUS "ASH"
	DEF PLAYERNAME3 EQUS "GIGI"
	DEF RIVALNAME1 EQUS "BLU"
	DEF RIVALNAME2 EQUS "GARY"
	DEF RIVALNAME3 EQUS "PIPPO"
ELIF DEF(_SPANISH)
	DEF PLAYERNAME1 EQUS "GUALDO"
	DEF PLAYERNAME2 EQUS "ASH"
	DEF PLAYERNAME3 EQUS "JAIME"
	DEF RIVALNAME1 EQUS "AZUL"
	DEF RIVALNAME2 EQUS "GARY"
	DEF RIVALNAME3 EQUS "JUAN"
ELSE
	DEF PLAYERNAME1 EQUS "YELLOW"
	DEF PLAYERNAME2 EQUS "ASH"
	DEF PLAYERNAME3 EQUS "JACK"
	DEF RIVALNAME1 EQUS "BLUE"
	DEF RIVALNAME2 EQUS "GARY"
	DEF RIVALNAME3 EQUS "JOHN"
ENDC
