; Shared noise instruments. Included once per compatible audio-engine bank.

INCLUDE "audio/sfx/noise_instrument01.asm"
INCLUDE "audio/sfx/noise_instrument02.asm"
INCLUDE "audio/sfx/noise_instrument03.asm"
INCLUDE "audio/sfx/noise_instrument04.asm"
INCLUDE "audio/sfx/noise_instrument05.asm"
INCLUDE "audio/sfx/noise_instrument06.asm"
INCLUDE "audio/sfx/noise_instrument07.asm"
INCLUDE "audio/sfx/noise_instrument08.asm"
INCLUDE "audio/sfx/noise_instrument09.asm"
INCLUDE "audio/sfx/noise_instrument10.asm"
INCLUDE "audio/sfx/noise_instrument11.asm"
INCLUDE "audio/sfx/noise_instrument12.asm"
INCLUDE "audio/sfx/noise_instrument13.asm"
INCLUDE "audio/sfx/noise_instrument14.asm"
INCLUDE "audio/sfx/noise_instrument15.asm"
INCLUDE "audio/sfx/noise_instrument16.asm"
INCLUDE "audio/sfx/noise_instrument17.asm"
INCLUDE "audio/sfx/noise_instrument18.asm"
INCLUDE "audio/sfx/noise_instrument19.asm"
