; Generated by tools/disassemble_gb_cfg.py; do not edit by hand.

SECTION "FR Startup Dispatch 01ab", ROM0[$01ab]

Block_01ab::
    cp $11
    jr z $01b2

SECTION "FR Startup Dispatch 01af", ROM0[$01af]

Block_01af::
    xor a
    jr $01b4

SECTION "FR Startup Dispatch 01b2", ROM0[$01b2]

Block_01b2::
    ld a, $01
    ldh [$ff00 + $fe], a
    jp $1d0c
