; Generated by tools/disassemble_gb_basic_block.py; do not edit by hand.
SECTION "Startup Main Block", ROM0[$1d94]

StartupMainBlock::
    call $1e16
    ld hl, $ff80
    ld bc, $007f
    call $16c6
    call $15b8
    ld a, $01
    ldh [$ff00 + $b8], a
    ld [$2000], a
    call $49e0
    xor a
    ldh [$ff00 + $d7], a
    ldh [$ff00 + $41], a
    ldh [$ff00 + $ae], a
    ldh [$ff00 + $af], a
    ldh [$ff00 + $0f], a
    ld [$c0f3], a
    ld [$c0f4], a
    ld a, $0d
    ldh [$ff00 + $ff], a
    ld a, $90
    ldh [$ff00 + $b0], a
    ldh [$ff00 + $4a], a
    ld a, $07
    ldh [$ff00 + $4b], a
    ld a, $ff
    ldh [$ff00 + $aa], a
    ld h, $98
    call $1b1e
    ld h, $9c
    call $1b1e
    ld a, $e3
    ldh [$ff00 + $40], a
    ld a, $10
    ldh [$ff00 + $8a], a
    call $1e20
    ei
    ld a, $40
    call $3ead
    ld a, $1f
    ld [$c0ef], a
    ld [$c0f0], a
    ld a, $9c
    ldh [$ff00 + $bd], a
    xor a
    ldh [$ff00 + $bc], a
    dec a
    ld [$cfb2], a
    ld a, $32
    call $3ead
    call $1597
    call $1e16
    call $3deb
    call $15b8
    ld a, $e3
    ldh [$ff00 + $40], a
    jp $416a

